### ISSUE TITLE
Upgrade PyO3 version?

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#140]
Is there a reason we keep relying `~pyo3-0.14.5` rather than `~0.16.4`? Upgrading might solve the problem we have with the Conda package: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=496568&view=logs&j=bb1c2637-64c6-57bd-9ea6-93823b2df951&t=350df31b-3291-5209-0bb7-031395f0baa1&l=559, see also https://github.com/conda-forge/pineappl-feedstock/pull/13.

**Comment by AleCandido** [comment]
No explicit reason I'm aware of.

The actual reason why it is like that I believe is that:
- `0.15.0` has been released on November 2021
- `0.16.0` has been released on February 2022

see https://github.com/PyO3/pyo3/releases

Now, while they only changed minor, PyO3 is still in the `0.x` phase, thus any minor update has to be considered as major.
Major upgrades should never happen silently, so there should be an explicit will to step into the new versions (and this is respected by the `^x.y.z` syntax in Javascript, and by `cargo` as default, i.e. even without caret).

So, the answer is that there has been no explicit will: it was working, no one took the burden to update it.

If you believe that now is relevant, update the requirement in the relevant `Cargo.toml`:
https://github.com/N3PDF/pineappl/blob/5e8bd410331a8042b279e1052f84b1f831b9fcab/pineappl_py/Cargo.toml#L29
test it and release.

(If you wish I can do as well, but not immediately, so I was inviting you to do it simply because you can; but if you prefer me to do it just wait and I'll do)

**Comment by cschwan** [comment]
Alright, I that case I'll try to upgrade it myself!

**Comment by cschwan** [comment]
Upgraded in commit 40e768a5965f47849f24e16a1f4b44f69f696386. To test the conda version we need another release, I suppose.

**Comment by AleCandido** [comment]
It would be nice to be able to test Conda packaging locally, but to make sure that it works in conda-forge it's likely there is no other way: we have to trigger a PR there (unless we can make a PR ourselves).

**Comment by cschwan** [comment]
@scarrazza is there a way to test https://github.com/conda-forge/pineappl-feedstock/pull/13 with additional fixes to PineAPPL *without* releasing a new version? If not I'll simply try to release 0.5.3 and delay every missing Issue to 0.5.4.
