### ISSUE TITLE
Fix Python documentation building

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#156]
We must update the Rust version in the container, because the build is failing: <https://readthedocs.org/projects/pineappl/builds/17395697/>. We should use Rust 1.56.1 which is our minimum supported Rust version (MSRV) for a while.

**Comment by AleCandido** [comment]
Ok, I'm on my way

**Comment by cschwan** [comment]
There's no need to rush with this one as it's Saturday and master doesn't have any significant changes and v0.5.4 is working :smile:.

**Comment by AleCandido** [comment]
Container v0.2.2 uploaded. Please @cschwan test it!

**Comment by AleCandido** [comment]
Current version of Rust is actually v1.62.0 inside the container, because:

https://github.com/N3PDF/pineappl/blob/master/pineappl_py/package/Containerfile#L19

means that I'm always using latest version available at generation time.

Should I pin instead the version of Rust in the `Containerfile` and manually upgrade? e.g. to run on the minimum supported instead of the latest (my guess is that there should be no need, because new versions of Rust v1 should be backward compatible, but I'd like to know your opinion).

**Comment by cschwan** [comment]
As long as it builds it's perfectly fine.

**Comment by AleCandido** [comment]
Ok, I found the way to retrigger without commiting:
![image](https://user-images.githubusercontent.com/10830876/178101535-22e3f909-cc49-4f45-aa49-fa9c94d97387.png)
(click the green button).

I'm testing it right now.

**Comment by AleCandido** [comment]
Ok, sorry, I'm too slow:

Actually being the problem ReadTheDocs, it doesn't care the less about the container...

RTD has its own workflow, and it is installing its version of Rust, specified here:
https://github.com/N3PDF/pineappl/blob/7b8fe17c39a49d2171560856bd303ebde9ff0d77/.readthedocs.yml#L11

Upgraded in 552dff4780ce5e4c0e037474391e662bb92ef54c

**Comment by cschwan** [comment]
Version `1.61` should be fine!

**Comment by AleCandido** [comment]
![Uploading image.png…]()

Should we close?

**Comment by cschwan** [comment]
Yes, thanks!
