### ISSUE TITLE
Add NNPDF4.0 FK table importer

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#70]
Specification is available here: https://docs.nnpdf.science/data/th-data-files.html.

**Comment by AleCandido** [comment]
I believe this not to be relevant any longer, do you agree @cschwan?

It would be not a simple task, because of everything we found out in the meanwhile, and we didn't schedule any conversion at this point.

**Comment by cschwan** [comment]
@AleCandido I don't think it's a priority Issue right now or even in the forseeable future, but I'd like to keep this open. Having the option of converting an FK table to a PineAPPL grid might be useful for debugging purposes in the future.

I think writing a converter would be quite easy, why do you think it wouldn't be?

**Comment by AleCandido** [comment]
Of course you have to take into account DIS vs hadronic, but I believe this is already included in what you call "quite easy".

But on top of what is currently inside a PineAPPL FkTable as well, you have to add at list the concatenation, that for 4.0 grids is inside, and for PineAPPL ones is outside (in the `yaml` recipe, together with compound).

Then, from my personal point of view, since the more this shifts to the future, the more PineAPPL FkTables will establish and replace 4.0 FkTables, I don't see a window in which this feature will be useful.
In any case, this is *my* point of view, so if you have a different feeling, keeping this open doesn't hurt.

**Comment by cschwan** [comment]
@AleCandido I don't quite follow what you said, but what I mean is simply a converter that takes FK tables in this format, https://docs.nnpdf.science/data/th-data-files.html, and converts them into PineAPPL grids, just like APPLgrids or fastNLO tables.

**Comment by AleCandido** [comment]
Ok, if you're able to do it, so much the better.

Just take into account that one old-style FkTable may correspond to multiple new FkTables.

**Comment by cschwan** [comment]
@AleCandido that's OK, I mainly need it for the positivity support for which we don't have any grids.
