### ISSUE TITLE
Clarify which uncertainties `convolute` and `pdfunc` shows

### ISSUE THREAD

**Issue by cschwan** [N3PDF/pineappl#99]
The subcommand `convolute` shows the two columns `neg unc` and `pos unc`, but it's not clear what this uncertainty is, see also https://github.com/NNPDF/runcards/pull/121#issuecomment-1010768710. We need to reflect that this shows the scale uncertainty.

**Comment by AleCandido** [comment]
Instead of `unc` an alternative name might be `var` (for *variation*, same number of letters).
Other, less appealing alternatives (to me) are: `scvar` (more letters), `scv` (barely comprehensible).

In any case, I believe we can call it in whatever way, the important thing is just to document the command, with a one/two-lines explanation of what are the fields (in the CLI help).

**Comment by cschwan** [comment]
I prefer it more explicitly: `scale uncertainty` and `PDF uncertainty`. By using two columns for these labels we only waste two characters in the first case and none in the second case.

**Comment by cschwan** [comment]
Commit d7bbf30f64a357b34f800e570f6c1c1b19bdba12 fixes this Issue.
